version: '3'
services:
  react-discovery:
    image: react-discovery
    build:
      args:
        CIRCLE_BRANCH: $CIRCLE_BRANCH
        REACT_APP_SEARCH_API_HOST: $REACT_APP_SEARCH_API_HOST
        REACT_APP_SEARCH_API_COLLECTION: $REACT_APP_SEARCH_API_COLLECTION
      context: ./packages/react-discovery-app
    container_name: react-discovery-app
    ports:
      - "5000:5000"

  e2e:
    image: cypress
    build:
      args:
        CIRCLE_BRANCH: $CIRCLE_BRANCH
      context: .
      dockerfile: Dockerfile-cypress
    container_name: cypress
    depends_on:
      - react-discovery
    environment:
      - CYPRESS_baseUrl=http://react-discovery:5000
      - CODECOV_TOKEN=$CODECOV_TOKEN
    command: bash -c "npx cypress run --browser chrome && npm run report"
