version: '3'
services:
  react-discovery:
    image: react-discovery
    build:
      args:
        CIRCLE_BRANCH: $CIRCLE_BRANCH
      context: ./packages/react-discovery-app
    container_name: react-discovery-app
    ports:
      - "5000:5000"

  e2e:
    image: cypress
    build: ./packages/react-discovery-tests
    container_name: cypress
    depends_on:
      - react-discovery
    environment:
      - CYPRESS_baseUrl=http://react-discovery:5000
    volumes:
      - ./packages/react-discovery-tests/cypress:/app/cypress
    command: npx cypress run --browser chrome
